### ISSUE TITLE
Countdown timer

### ISSUE THREAD

**Issue by mcdoash** [CentralProgramming/CentralProgramming.github.io#11]
So I've added a countdown to the first meeting on the main page (right now the date is set to the first day of school). Please let me know what you think! Here's a picture of it. If you click the "x" you can make it disappear.

<img width="343" alt="countdown" src="https://user-images.githubusercontent.com/29292463/28333074-d7d840aa-6bc4-11e7-8582-359d9241dbd1.png">

If you like it and think we should keep it then I do have a concern about its positioning. It starts on the top left corner like this:

<img width="1439" alt="central_programming" src="https://user-images.githubusercontent.com/29292463/28333165-16ba0a74-6bc5-11e7-9eec-154b2ba295e8.png">

And then when you scroll down it sticks to the nav bar like this:

<img width="1436" alt="central_programming" src="https://user-images.githubusercontent.com/29292463/28333027-b3d0432e-6bc4-11e7-9bb0-01bed1da1100.png">

Please let me know what you think about the positioning and the countdown in general!

**Comment by AngelaZ0** [comment]
I think it looks great, but I think it's better to move the countdown a little bit up, maybe closer to the left hand corner?

**Comment by mcdoash** [comment]
@AngelaZ0 do you mean like this?

<img width="1439" alt="central_programming" src="https://user-images.githubusercontent.com/29292463/28341478-f07192a2-6be1-11e7-96d0-b060dbda9c0f.png">

<img width="638" alt="central_programming" src="https://user-images.githubusercontent.com/29292463/28341456-cb2e1d4e-6be1-11e7-8a38-05f205df163c.png">

The reason I had it so far to the right was so that it was centered, but I like this way too. Unless you were referring to something else???

**Comment by Amyffz** [comment]
can you make it a tad bit smaller so it fits inside the black bar

**Comment by AngelaZ0** [comment]
Sorry, I mean the same thing as Amy said, make the tab fits inside the black bar

**Comment by mcdoash** [comment]
Oh!!! Yeah, sure! How's this?

<img width="646" alt="central_programming" src="https://user-images.githubusercontent.com/29292463/28383236-cab5dcd2-6c8e-11e7-9edd-9c1d13c87306.png">

**Comment by AngelaZ0** [comment]
Yeah,looks good!

**Comment by mcdoash** [comment]
So, when trying to make it responsive (so when you resize the window/view on other devices it looks ok) I realized I need to change the positioning.

Here it is at the full width of my laptop (1440px):

<img width="855" alt="central_programming" src="https://user-images.githubusercontent.com/29292463/28397599-9635e370-6cd0-11e7-98ad-8ded3aff780c.png">

Right before it covers the navigation menu (1201px):

<img width="496" alt="central_programming" src="https://user-images.githubusercontent.com/29292463/28397615-b5543a5e-6cd0-11e7-931a-ec3abf99b048.png">

And after it would start getting in the way of the navigation menu (<1200px):

<img width="567" alt="central_programming" src="https://user-images.githubusercontent.com/29292463/28397630-d31ffc80-6cd0-11e7-9962-a73b33ccbd2f.png">

Thoughts? It's not centered anymore. Does that make it look off? Since you can click it to make it go away I don't think it will be too much of a hassle at smaller widths.

**Comment by Amyffz** [comment]
should be fine for now

On Jul 19, 2017, at 10:27 PM, Ash <notifications@github.com<mailto:notifications@github.com>> wrote:


So, when trying to make it responsive (so when you resize the window/view on other devices it looks ok) I realized I need to change the positioning.

Here it is at the full width of my laptop (1440px):

[central_programming]<https://user-images.githubusercontent.com/29292463/28397599-9635e370-6cd0-11e7-98ad-8ded3aff780c.png>

Right before it covers the navigation menu (1201px):

[central_programming]<https://user-images.githubusercontent.com/29292463/28397615-b5543a5e-6cd0-11e7-931a-ec3abf99b048.png>

And after it would start getting in the way of the navigation menu (<1200px):

[central_programming]<https://user-images.githubusercontent.com/29292463/28397630-d31ffc80-6cd0-11e7-9962-a73b33ccbd2f.png>

Thoughts? It's not centered anymore. Does that make it look off? Since you can click it to make it go away I don't think it will be too much of a hassle at smaller widths.

**Comment by mcdoash** [comment]
In the future would it be better in another way though?
