### ISSUE TITLE
Evil navbar isn't responsive

### ISSUE THREAD

**Issue by mcdoash** [CentralProgramming/CentralProgramming.github.io#14]
The navigation menu hates me. It took me forever to get it reworked but I can't get it completely responsive.

When the screen is too small all the links but "Home" disappear and when you click on the icon that pops up the links are *supposed* to expand, but they don't for some reason.

<img width="330" alt="central_programming_and_central_programming" src="https://user-images.githubusercontent.com/29292463/28443549-c945413e-6d84-11e7-8e0a-0ee8278592cd.png">

I'm looking into it right now.

**Comment by mcdoash** [comment]
It's finally complete!!! This was probably the biggest challange I've had so far, but after a couple of hours of experimenting I've finally figured it out. Now all that's left is deciding on the design.

Here it is right now:

<img width="672" alt="navbar" src="https://user-images.githubusercontent.com/29292463/28541961-ac5e00b8-7088-11e7-93c7-708f167bb5ce.png">

I changed the colours on the resource section so that it stands out more. Here are some alternative versions. Please let me know which you like best or any other suggestions. @Fay-Z @Amyffz @AngelaZ0 

<img width="669" alt="central_programming" src="https://user-images.githubusercontent.com/29292463/28542043-f5b5a810-7088-11e7-86e5-2af10951f85a.png">
<img width="669" alt="central_programming" src="https://user-images.githubusercontent.com/29292463/28542204-61c315ba-7089-11e7-821b-980f2dac3f9b.png">
<img width="669" alt="central_programming" src="https://user-images.githubusercontent.com/29292463/28542214-6c7638fc-7089-11e7-9b33-56d83667ff18.png">

**Comment by mcdoash** [comment]
Or I could remove the "dropdown" links (Array List, Array, etc.) and have resources behave like the rest of the links? The picture below shows what I mean (the mouse is hovering over Resources).

<img width="672" alt="central_programming" src="https://user-images.githubusercontent.com/29292463/28542620-cbce8740-708a-11e7-9250-7f25a5595403.png">

**Comment by mcdoash** [comment]
Lastly, I could put the "dropdown" links underneath the Resources link:

<img width="672" alt="central_programming" src="https://user-images.githubusercontent.com/29292463/28542706-24125d14-708b-11e7-8455-708935f20939.png">

Which looks like this when really small:

<img width="326" alt="central_programming" src="https://user-images.githubusercontent.com/29292463/28542880-e5f380fc-708b-11e7-9b19-3d43556cfb21.png">

**Comment by mcdoash** [comment]
I like the last one the best, personally.

**Comment by Amyffz** [comment]
I'm fine with any

Sent from BlueMail<http://www.bluemail.me/r?b=10066>
On Jul 24, 2017, at 4:02 PM, Ash <notifications@github.com<mailto:notifications@github.com>> wrote:

It's finally complete!!! This was probably the biggest challange I've had so far, but after a couple of hours of experimenting I've finally figured it out. Now all that's left is deciding on the design.

Here it is right now:

[navbar]<https://user-images.githubusercontent.com/29292463/28541961-ac5e00b8-7088-11e7-93c7-708f167bb5ce.png>

I changed the colours on the resource section so that it stands out more. Here are some alternative versions. Please let me know which you like best or any other suggestions. @Fay-Z<https://github.com/fay-z> @Amyffz<https://github.com/amyffz> @AngelaZ0<https://github.com/angelaz0>

[central_programming]<https://user-images.githubusercontent.com/29292463/28542043-f5b5a810-7088-11e7-86e5-2af10951f85a.png>

[central_programming]<https://user-images.githubusercontent.com/29292463/28542204-61c315ba-7089-11e7-821b-980f2dac3f9b.png>

[central_programming]<https://user-images.githubusercontent.com/29292463/28542214-6c7638fc-7089-11e7-9b33-56d83667ff18.png>

**Comment by AngelaZ0** [comment]
I like the last one
